#!/bin/bash -e
echo "Releasing on Maven Central ..."
./gradlew clean test publish -PmavSigning=true -PmavPublishToRemoteRepo=true --max-workers 1

version=$(cat manifest.gradle | grep "library_version" | tr "'" '\n' | head -n 2 | tail -n 1)

function generate-debug-apk {
    rm -rf *.apk
    cd app
    ./gradlew clean assembleDebug
    cp demo/build/outputs/apk/debug/demo-debug.apk ../"recycler-adapter-demo-debug-$version.apk"
    cd ..
}

echo "Generating Demo Apk ..."
generate-debug-apk

APK=$(ls *.apk | head -n 1)

echo "Creating GitHub Release ..."
hub release create -a "$APK" -m "$version" "$version"

echo
echo "Done!"
echo "Visit https://oss.sonatype.org/#stagingRepositories and confirm the release"
